version: "3"
services:
  swc:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    container_name: swc-web-server
    ports:
      - "8080:8080"
    env_file:
      - .env
#    environment:
#      - MONGO_URL
#      - RUST_LOG
#      - HOST
#      - PORT
